import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import styles from "../styles/Home.module.css";
import icon from "../public/static/images/momoko_Cup_of_Coffee_with_Sack_of_Coffee_Beans_3.svg";

const Home: NextPage = () => {
  const handleOnBannerBtnClick = () => {
    console.log("button click");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="../public/static/images/momoko_Cup_of_Coffee_with_Sack_of_Coffee_Beans_3.svg"
        />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText="Viev stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
      </main>
    </div>
  );
};
export default Home;
